services:
    nginx:
        image:
	mariadb:
		image: mariadb
		environment:
			SQL_DATABASE:		${SQL_DATABASE}
			SQL_ADMIN:			${SQL_ADMIN}
			SQL_USER			${SQL_USER}
			SQL_ADMIN_PASSWORD	${SQL_ADMIN_PASSWORD}
			SQL_USER_PASSWORD	${SQL_USER_PASSWORD}
			SQL_ROOT_PASSWORD	${SQL_ROOT_PASSWORD}
