CREATE DATABASE IF NOT EXISTS '$SQL_DATABASE' CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS '$SQL_ADMIN'@'%' IDENTIFIED BY '$SQL_ADMIN_PASSWORD';
CREATE USER IF NOT EXISTS '$SQL_USER'@'%' IDENTIFIED BY '$SQL_USER_PASSWORD';
GRANT ALL PRIVILEGES ON '$SQL_DATABASE'.* TO '$SQL_ADMIN'@'%' IDENTIFIED BY '$SQL_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$SQL_ROOT_PASSWORD' WITH GRAND OPTION;
ALTER USER 'root'@'%' IDENTIFIED BY '$SQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;
